#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

GREEN='\033[32m'
RED='\033[31m'
RESET='\033[0m'

echo "${GREEN}Running Commitlint...${RESET}"
npx commitlint --edit $1

if [ $? -eq 0 ]; then
  echo "${GREEN}Commit Lint checks passed!${RESET}"
  exit 0
else
  echo "${GREEN}Commit Lint checks failed! Please fix the format off commit massage.${RESET}"
  exit 1
fi