#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

GREEN='\033[32m'
RED='\033[31m'
RESET='\033[0m'

echo "${GREEN}Running lint-staged...${RESET}"
npx lint-staged


if [ $? -eq 0 ]; then
  echo "${GREEN}Pre-commit checks passed!${RESET}"
  exit 0
else
  echo "${RED}Pre-commit checks failed! Please fix the issues before committing.${RESET}"
  exit 1
fi